apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: app-infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres-db
        image: postgres
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            memory: "4Gi"
            cpu: "4"
        env:
        - name: POSTGRES_DB
          value: yourappdb
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: max_connections
          value: "200"
        - name: shared_buffers
          value: "1GB"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 30
          periodSeconds: 20
        startupProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          failureThreshold: 30
          periodSeconds: 10
      volumes:
      - name: postgres-storage
        hostPath:
          path: /home/arav/Desktop/Sarvam AI/data/postgres-data
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: app-infrastructure
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: app-infrastructure
type: Opaque
stringData:
  POSTGRES_PASSWORD: sarvam_litmus_test

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  namespace: app-infrastructure
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
  type: NodePort